export const jobPosts = [
  {
    title: 'Senior Frontend Developer',
    companyName: 'Tech Co',
    positions: ['Senior', 'Developer', 'Frontend'],
    postedAgo: '2 days ago',
    location: 'San Francisco, CA',
    salaryRange: '₹80,000 - ₹100,000',
    isFeatured: true,
    isNew: false,
  },
  {
    title: 'Backend Engineer',
    companyName: 'Data Solutions Ltd',
    positions: ['Developer', 'Backend'],
    postedAgo: '1 week ago',
    location: 'New York, NY',
    salaryRange: '₹90,000 - ₹110,000',
    isFeatured: false,
    isNew: true,
  },
  {
    title: 'Data Analyst',
    companyName: 'Analytics Inc',
    positions: ['Analyst'],
    postedAgo: '3 days ago',
    location: 'Seattle, WA',
    salaryRange: '₹70,000 - ₹90,000',
    isFeatured: true,
    isNew: false,
  },
  {
    title: 'Full Stack Developer',
    companyName: 'Web Solutions Co',
    positions: ['Developer', 'Full Stack'],
    postedAgo: '4 days ago',
    location: 'Austin, TX',
    salaryRange: '₹85,000 - ₹105,000',
    isFeatured: false,
    isNew: true,
  },
  {
    title: 'UX/UI Designer',
    companyName: 'Creative Designs Ltd',
    positions: ['Designer', 'UX', 'UI'],
    postedAgo: '5 days ago',
    location: 'Los Angeles, CA',
    salaryRange: '₹75,000 - ₹95,000',
    isFeatured: true,
    isNew: false,
  },
  {
    title: 'Software Engineer',
    companyName: 'Tech Innovators Inc',
    positions: ['Developer', 'Software'],
    postedAgo: '2 weeks ago',
    location: 'Chicago, IL',
    salaryRange: '₹88,000 - ₹108,000',
    isFeatured: false,
    isNew: false,
  },
  {
    title: 'Product Manager',
    companyName: 'Productive Solutions Co',
    positions: ['Manager', 'Product'],
    postedAgo: '6 days ago',
    location: 'Boston, MA',
    salaryRange: '₹95,000 - ₹115,000',
    isFeatured: false,
    isNew: true,
  },
  {
    title: 'Security Analyst',
    companyName: 'Secure Systems Ltd',
    positions: ['Analyst', 'Security'],
    postedAgo: '1 day ago',
    location: 'Denver, CO',
    salaryRange: '₹80,000 - ₹100,000',
    isFeatured: true,
    isNew: false,
  },
  {
    title: 'Machine Learning Engineer',
    companyName: 'AI Innovations Inc',
    positions: ['Developer', 'Machine Learning'],
    postedAgo: '3 weeks ago',
    location: 'Portland, OR',
    salaryRange: '₹90,000 - ₹110,000',
    isFeatured: false,
    isNew: false,
  },
  {
    title: 'Marketing Specialist',
    companyName: 'Digital Marketing Co',
    positions: ['Specialist', 'Marketing'],
    postedAgo: '7 days ago',
    location: 'Miami, FL',
    salaryRange: '₹70,000 - ₹90,000',
    isFeatured: true,
    isNew: true,
  },
]
