export const jobPosts = [
  {
    title: 'Senior Frontend Developer',
    companyName: 'Tech Co',
    positions: ['Senior', 'Developer'],
    postedAgo: '2 days ago',
    location: 'San Francisco, CA',
    salaryRange: '$80K - $100K',
    isFeatured: true,
    isNew: false,
    isAd: true,
    benefits: [
      'Flexible work hours',
      'Health insurance',
      'Remote-first culture',
    ],
    type: 'full-time',
  },
  {
    title: 'Backend Engineer',
    companyName: 'Data Solutions Ltd',
    positions: ['Developer', 'Backend'],
    postedAgo: '1 week ago',
    location: 'New York, NY',
    salaryRange: '$90K - $110K',
    isFeatured: false,
    isNew: true,
    isAd: true,
    benefits: [
      'Competitive salary',
      '401(k) matching',
      'Professional development',
    ],
    type: 'contract',
  },
  {
    title: 'Data Analyst',
    companyName: 'Analytics Inc',
    positions: ['Analyst'],
    postedAgo: '3 days ago',
    location: 'Seattle, WA',
    salaryRange: '$70K - $90K',
    isFeatured: true,
    isNew: false,
    benefits: ['Remote work options', 'Wellness programs', 'Paid time off'],
    type: 'full-time',
  },
  {
    title: 'Full Stack Developer',
    companyName: 'Web Solutions Co',
    positions: ['Developer', 'Full Stack'],
    postedAgo: '4 days ago',
    location: 'Austin, TX',
    salaryRange: '$85k - $105k',
    isFeatured: false,
    isNew: true,
    benefits: [
      'Flexible work environment',
      'Health and dental benefits',
      'Career growth opportunities',
    ],
    type: 'part-time',
  },
  {
    title: 'UX/UI Designer',
    companyName: 'Creative Designs Ltd',
    positions: ['Designer', 'UX', 'UI'],
    postedAgo: '5 days ago',
    location: 'Los Angeles, CA',
    salaryRange: '$75k - $95k',
    isFeatured: true,
    isNew: false,
    benefits: [
      'Remote work flexibility',
      'Team collaboration',
      'Training and development programs',
    ],
    type: 'full-time',
  },
  {
    title: 'Software Engineer',
    companyName: 'Tech Innovators Inc',
    positions: ['Developer', 'Software'],
    postedAgo: '2 weeks ago',
    location: 'Chicago, IL',
    salaryRange: '$88k - $108k',
    isFeatured: false,
    isNew: false,
    benefits: [
      'Competitive compensation',
      'Work-life balance',
      'Remote-friendly culture',
    ],
    type: 'intern',
  },
  {
    title: 'Product Manager',
    companyName: 'Productive Solutions Co',
    positions: ['Manager', 'Product'],
    postedAgo: '6 days ago',
    location: 'Boston, MA',
    salaryRange: '$95k - $115k',
    isFeatured: false,
    isNew: true,
    benefits: [
      'Remote work options',
      'Health and wellness programs',
      '401(k) plan',
    ],
    type: 'full-time',
  },
  {
    title: 'Security Analyst',
    companyName: 'Secure Systems Ltd',
    positions: ['Analyst', 'Security'],
    postedAgo: '1 day ago',
    location: 'Denver, CO',
    salaryRange: '$80K - $100K',
    isFeatured: true,
    isNew: false,
    benefits: [
      'Flexible scheduling',
      'Health benefits',
      'Professional development opportunities',
    ],
    type: 'full-time',
  },
  {
    title: 'Machine Learning Engineer',
    companyName: 'AI Innovations Inc',
    positions: ['Developer', 'Machine Learning'],
    postedAgo: '3 weeks ago',
    location: 'Portland, OR',
    salaryRange: '$90K - $110K',
    isFeatured: false,
    isNew: false,
    benefits: [
      'Remote work flexibility',
      'Competitive salary',
      'Learning and growth opportunities',
    ],
    type: 'freelance',
  },
  {
    title: 'Marketing Specialist',
    companyName: 'Digital Marketing Co',
    positions: ['Specialist', 'Marketing'],
    postedAgo: '7 days ago',
    location: 'Miami, FL',
    salaryRange: '$70K - $90K',
    isFeatured: true,
    isNew: true,
    benefits: [
      'Flexible work arrangements',
      'Health and wellness benefits',
      'Career advancement opportunities',
    ],
    type: 'full-time',
  },
]
